language: ruby
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  chrome: stable
sudo: required
notifications:
  recipients:
    - tanle.oz@gmail.com
