language: ruby
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - gem install bundler
notifications:
  recipients:
    - tanle.oz@gmail.com
